# 基本的系统
name: base os

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: show user name
        run: |
          whoami
      
      - name: show ubuntu version
        run: sudo cat /proc/version
        
      - name: install zerotier
        env:
          ZEROTIER_ID: ${{ secrets.ZEROTIER_ID }}
        run: |
          curl -s https://install.zerotier.com | sudo bash
          sudo zerotier-cli join "$ZEROTIER_ID"

      - name: install tcl tk expect
        run: |
          sudo apt install tcl tk expect
          
      - name:  middify root and runner user password
        run: |
          sh common/middify_password.sh
          
      - name:  middify root and runner user password
        run: |
          sudo bash common/install_samba.sh
          
      - name:  keeplive session
        run: |
          sh common/keeplive_session.sh
