# 基本的系统
name: base os

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: show user name
        run: |
          whoami
      - name: install tcl tk expect
        run: |
          sudo apt install tcl tk expect
          
      # - name: install zerotier
      #   env:
      #     ZEROTIER_ID: ${{ secrets.ZEROTIER_ID }}
      #   run: |
      #     curl -s https://install.zerotier.com | sudo bash
      #     sudo zerotier-cli join "$ZEROTIER_ID"
          
      - name:  middify root and runner user password
        env:
          PWD: ${{ secrets.PWD }}
        run: |
          sh common/middify_password.sh "$PWD"

      - name:  keeplive session
        run: |
          sh common/keeplive_session.sh
