name: windown-latest
on:
  workflow_dispatch:
jobs:
  task-1:
    uses: ./.github/workflows/win_tmp.yml
    with:
      zerotier_token: ${{ secrets.ZEROTIER_TOKEN }}
      zerotier_id: ${{ secrets.ZEROTIER_ID }}
      wx_push_app_token: ${{ secrets.WX_PUSH_APP_TOKEN }}
      wx_uid: ${{ secrets.WX_UID }}
