name: windown-latest
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: install sougou pinyin wubi
      run: |
        Write-Host "downloading wubi soft"
        $wubiPath = "$env:TEMP\wubi.exe"
        Invoke-WebRequest -Uri "https://github.com/findnr/actions_os/releases/download/untagged-2957a38f3ab1a2a115ec/sougouwubi.exe" -OutFile $installerPath
        Write-Host "install wubi working..."
        Start-Process -FilePath $wubiPath -ArgumentList "/S" -Wait
        Write-Host "downloading wubi soft"
        $pinyinPath = "$env:TEMP\pinyin.exe"
        Invoke-WebRequest -Uri "https://github.com/findnr/actions_os/releases/download/untagged-2957a38f3ab1a2a115ec/sougoupinyin.exe" -OutFile $installerPath
        Write-Host "install pinyin working..."
        Start-Process -FilePath $pinyinPath -ArgumentList "/S" -Wait
    - name: setting info qaz,123456
      env:
        ZEROTIER_ID: ${{ secrets.ZEROTIER_ID }}
      run: |
         $env:USERNAME
         Write-Host "downloading ZeroTier msi progra..."
         $installerPath = "$env:TEMP\ZeroTierInstaller.msi"
         Invoke-WebRequest -Uri "https://download.zerotier.com/dist/ZeroTier%20One.msi" -OutFile $installerPath
         Write-Host "install working ZeroTier..."
         Start-Process -FilePath "msiexec.exe" -ArgumentList "/i $installerPath /qn /norestart" -Wait
         cd 'C:\Program Files (x86)\ZeroTier\One\'
         ./zerotier_desktop_ui.exe
         Start-Sleep -Seconds 60
         ./zerotier-cli join "${env:ZEROTIER_ID}"
         Start-Sleep -Seconds 10
         ./zerotier-cli info
         ipconfig
         $currentUsername = $env:USERNAME
         $defaultPassword = ConvertTo-SecureString "qaz,123456" -AsPlainText -Force
         Set-LocalUser -Name $currentUsername -Password $defaultPassword
         Start-Sleep -Seconds 25200
