name: windown-latest
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: install sougou wubi
      run: |
        $url = "https://api.github.com/repos/${{ github.repository }}/releases/latest"
        $release = Invoke-RestMethod -Uri $url -Headers @{"Authorization"="Bearer ${{ secrets.GITHUB_TOKEN }}"} 
        $downloadUrl = $release.assets | Where-Object { $_.name -eq "sougouwubi.exe" } | Select-Object -ExpandProperty browser_download_url
        Invoke-WebRequest -Uri $downloadUrl -OutFile sougouwubi.exe
        # Start-Process -FilePath "D:\a\actions_os\actions_os\sougouwubi.exe" -ArgumentList "/S" -Wait -NoNewWindow
    - name: install sougou pinyin
      run: | 
        $url = "https://api.github.com/repos/${{ github.repository }}/releases/latest"
        $release = Invoke-RestMethod -Uri $url -Headers @{"Authorization"="Bearer ${{ secrets.GITHUB_TOKEN }}"} 
        $downloadUrl = $release.assets | Where-Object { $_.name -eq "sougoupinyin.exe" } | Select-Object -ExpandProperty browser_download_url
        Invoke-WebRequest -Uri $downloadUrl -OutFile "sougoupinyin.exe"
        # Start-Process -FilePath "D:\a\actions_os\actions_os\sougoupinyin.exe" -ArgumentList "/S" -Wait -NoNewWindow
       
    - name: setting info qaz,123456
      env:
        ZEROTIER_ID: ${{ secrets.ZEROTIER_ID }}
      run: |
         $env:USERNAME
         Write-Host "downloading ZeroTier msi progra..."
         $installerPath = "$env:TEMP\ZeroTierInstaller.msi"
         Invoke-WebRequest -Uri "https://download.zerotier.com/dist/ZeroTier%20One.msi" -OutFile $installerPath
         Write-Host "install working ZeroTier..."
         Start-Process -FilePath "msiexec.exe" -ArgumentList "/i $installerPath /qn /norestart" -Wait
         cd 'C:\Program Files (x86)\ZeroTier\One\'
         ./zerotier_desktop_ui.exe
         Start-Sleep -Seconds 60
         ./zerotier-cli join "${env:ZEROTIER_ID}"
         Start-Sleep -Seconds 10
         ./zerotier-cli info
         ipconfig
         $currentUsername = $env:USERNAME
         $defaultPassword = ConvertTo-SecureString "qaz,123456" -AsPlainText -Force
         Set-LocalUser -Name $currentUsername -Password $defaultPassword
         Start-Sleep -Seconds 60
    - name: delete network node
      env:
        ZEROTIER_ID: ${{ secrets.ZEROTIER_ID }}
        ZEROTIER_TOKEN: ${{ secrets.ZEROTIER_TOKEN }}
      run: |
        $response = Invoke-RestMethod -Uri "https://api.zerotier.com/api/v1/network/${env:ZEROTIER_ID}/member" -Headers @{"Authorization" = "token ${env:ZEROTIER_TOKEN}"} -Method Get -ContentType "application/json"
        $networkAdapter = Get-NetIPAddress -InterfaceAlias "*One*" -AddressFamily IPv4
        foreach ($item in $response) {
            if ($item.config.ipAssignments -eq $networkAdapter.IPAddress) {
                $response = Invoke-RestMethod -Uri "https://api.zerotier.com/api/v1/network/${env:ZEROTIER_ID}/member/$item.nodeId" -Headers @{"Authorization" = "token ${env:ZEROTIER_TOKEN}"} -Method Delete
                Write-Output $item.nodeId
            } else {
                Write-Output "Strings are not equal"
            }
        }
