name: windown-latest
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: windows-latest
    steps:
    - uses: ./.github/workflows/win_tmp.yml
      env:
        zerotier_token: ${{ secrets.ZEROTIER_TOKEN }}
        zerotier_id: ${{ secrets.ZEROTIER_ID }}
        wx_push_app_token: ${{ secrets.WX_PUSH_APP_TOKEN }}
        wx_uid: ${{ secrets.WX_UID }}
      with:
        zerotier_token: ${env:zerotier_token}
        zerotier_id: ${env:zerotier_id}
        wx_push_app_token: ${env:wx_push_app_token}
        wx_uid: ${env:wx_uid}
